language: python
python:
  - "3.4"
  - "2.7"
install:
  - pip install -r dev-requirements.txt
  - pip install coveralls
script:
  - python setup.py install
  - nosetests --with-coverage --cover-package=pyimeji
after_success:
  - coveralls
